spring.application.name=uco-parking-backend
server.port=8080

ucoparking.db.url=jdbc:sqlserver://localhost:1433;databaseName=ucoParkingDB;encrypt=false;trustServerCertificate=true
ucoparking.db.usuario=sa
ucoparking.db.contrasena=UcoParking123!
ucoparking.db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
